<h2>.komitees</h2>
<b>Abi-Motto:</b><br>
<u>David Keppeler (13/2)</u>, Sebastian Koch (13/1), Katharina Burkhardt (13/3), Kirsten Hipp (13/3) Angelika Kern (13/3), Mustafa Sert (13/5), Christoph Nann (13/5), Steffen Zietkowski (13/5)
<br>
<br>
<b>Abi-Ball:</b><br>
<u>Manuel Müller (13/2)</u>, Deborah Buck (13/3), Lisa Fesseler (13/3), Heike Gunst (13/3), Kirsten Hipp (13/3), Kerstin Kocher (13/3), Julia Reichert (13/3), Karina Volk (13/3), Manuela Haap (13/2), Martina Katz (13/1), Alina Katzmann (13/1), Carolin Kratt (13/1), Sina Mandl (13/1) 
<br>
<br>
<b>Abi-Zeitung:</b><br>
<u>Petra Hamacher (13/5)</u>, Denis Stier (13/5), Ana-Tamara Fries (13/4), Laura Jäcksch (13/4), Katinka Lange (13/4), Sonia Munoz-Dominguez (13/4), Annika Rechlitz (13/4), Anja Scherer (13/4), Juliane Silberzahn (13/4), Sonja Ulmer (13/4), Fatima Giuliano (13/3), Hannah Humpf (13/2), Andrea Hertkorn (13/2), Colin Schneider (13/1), Dana Böckle (13/1)
<br>
<br>
<b>Abi-Hütte:</b><br>
<u>Gudrun Wilhelm (13/1)</u>, Christin Teufel (13/1), Fatima Giuliano (13/3)
<br>
<br>
<b>Abi-Vorfest:</b><br>
<u>Manuel Müller (13/2)</u>, Philipp Mehl (13/2), Karl Schmidt (13/2), Matthias Rubin-Schwarz (13/2)
<br>
<br>
<b>Abi-Band:</b><br>
<u>Sebastian Koch (13/1)</u>, Fatima Giuliano (13/3), Phillip Kondic (13/2), Herr Michel 
<br>
<br>
<b>Abi-Streich:</b><br>
<u>Karolina Kos (13/3)</u>, Anja Löffel (13/3), Jasmin Gutbrod (13/3), Oliver Fink (13/1), Christin Teufel (13/1), Sebastian Engel (13/5), Steffen Zietkowski (13/5)
<br>
<br>
<b>Zentralkomitee:</b><br>
Sebastian Koch (13/1), Philipp Mehl (13/2), Matthias Rubin-Schwarz (13/2)
<br>
<br>
<b>Abi-Konto:</b><br>
Florian Deiß (13/4)
<br>
<br>
<b>Abi-Website:</b><br>
Sebastian Engel (13/5)
