<h2>.impressum</h2>

Abiturienten der Wilhelm-Schickard-Schule Tübingen 2005<br>
Ansprechpartner:<br>
Sebastian Engel<br>
Argonnenstraße 6<br>
72108 Rottenburg<br>
<br>
Tel.: 07472/24651<br>
Fax.: 07472/24651<br>
E-Mail: <a href="mailto:webmaster@nachderschule.com">webmaster@nachderschule.com</a><br>
<br>
<br>
<br>
Wir distanzieren uns hiermit ausdrücklich von allen Inhalten der auf dieser Website gelinkten Internetseiten, da wir auf die Inhalte keinerlei Einfluß haben!