<h2>.links</h2>
<h4><b>Offizielle Websites:</b></h4>
<a href="http://www.wss.tue.bw.schule.de/" target="_blank">http://www.wss.tue.bw.schule.de/</a>&nbsp;&nbsp;&nbsp;//unsere Schule<br>

<h4><b>Schüler-Websites:</b></h4>
<a href="http://www.sebastian-engel.de" target="_blank">http://www.sebastian-engel.de</a>&nbsp;&nbsp;&nbsp;//Webmaster<br>
<a href="http://www.inoxonline.de" target="_blank">http://www.inoxonline.de</a>&nbsp;&nbsp;&nbsp;//WG-Schülersprecher<br>


<br>
<center>
<table width="90%">
 <tr>
  <td>
   <div align="left">
   Wir distanzieren uns hiermit ausdrücklich von allen Inhalten der auf dieser Website gelinkten Internetseiten, da wir auf die Inhalte keinerlei Einfluß haben!
   </div>
  </td>
 </tr>
</table>
</center>