<h2>.news</h2>
22.12.2004:<br>
Nun könnt ihr eure Personenbeschreibungen hochladen!<br>
Ansehen können sie allerdings nur die Mitglieder des Abi-Zeitungs-Kommittees!
<br>
<br>
07.12.2004:<br>
Abi-Website Grundgerüst steht! Jetzt fehlt "nur" noch:<br>
- das Forum<br>
- das Gästebuch<br>
- ein Newsscript<br>
- ein Passwort-Bereich<br>
- ein Design<br>
- der Inhalt<br>
<br>
... aber sonst ists schon recht weit! :)
